services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      ORIGIN: http://localhost:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
